name: Release
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

jobs:
  build:
    name: Release kernel
    uses: ./.github/workflows/build.yml

  releaser:
    needs: [build]
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@main
        with:
           merge-multiple: true
           path: /home/runner

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%m/%d/%Y')"

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{steps.date.outputs.date}}"
          tag_name: "${{steps.date.outputs.date}}"
          prerelease: false
          files: /home/runner/AOSP*.zip
